# Generated by Django 5.0.4 on 2024-04-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 23, 22, 2, 36, 471850), verbose_name='Опубликована'),
        ),
    ]
